### ISSUE TITLE
npm install -d failed

### ISSUE THREAD

**Issue by Hackerline** [killme2008/node-zk-browser#11]
make: Entering directory `/opt/apps_install/node-zk-browser-0.1.0/node_modules/zookeeper/build'
  ACTION binding_gyp_libzk_target_build_zk_client_lib .
Downloading zookeeper-3.4.3 from http://apache.mirrors.tds.net/zookeeper/zookeeper-3.4.3/zookeeper-3.4.3.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error exit delayed from previous errors
Unable to build zookeeper library
make: *** [.] Error 1
make: Leaving directory `/opt/apps_install/node-zk-browser-0.1.0/node_modules/zookeeper/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/apps_install/node-v4.2.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.18-371.3.1.el5xen
gyp ERR! command "/opt/apps_install/node-v4.2.1-linux-x64/bin/node" "/opt/apps_install/node-v4.2.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/apps_install/node-zk-browser-0.1.0/node_modules/zookeeper
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm info zookeeper@3.4.6 Failed to exec install script
npm ERR! Linux 2.6.18-371.3.1.el5xen
npm ERR! argv "/opt/apps_install/node-v4.2.1-linux-x64/bin/node" "/opt/apps_install/node-v4.2.1-linux-x64/bin/npm" "install" "-d"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! zookeeper@3.4.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zookeeper@3.4.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zookeeper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zookeeper
npm ERR! There is likely additional logging output above.
npm info preuninstall zookeeper@3.4.6
npm info uninstall zookeeper@3.4.6
npm info postuninstall zookeeper@3.4.6

npm ERR! Please include the following file with any support request:

how to deal with it ?

**Comment by zqhxuyuan** [comment]
zookeeper版本不对， 有个pr说改成*， 就可以了

```
{
  "name": "node-zk-browser",
  "version": "0.0.2",
  "dependencies": {
    "ejs": "0.7.2",
    "express": "3.2.6",
    "zookeeper":"*",
    "express-namespace":"0.1.1"
  }
}
```

**Comment by yosaku01** [comment]
You need use node.js v5.9.1 and zookeeper 3.4.8-2
